language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
addons:
   postgresql: "9.3"
env:
  - DB_TESTING: 1
before_install:
   - "cpanm DBI"
   - "cpanm DBD::Pg"
   - "cpanm Try::Tiny"
   - "cpanm Memoize"
   - "cpanm Test::More"
   - "cpanm Test::Trap"
   - "cpanm Test::Exception"
   - "cpanm Devel::Cover::Report::Coveralls"
   - "cpanm Data::Dumper"
   - "cpanm Log::Log4perl"
   - "cpanm Locale::Maketext"
   - "cpanm DateTime"
   - "cpanm Locale::Maketext::Lexicon"
   - "cpanm MIME::Base64"
   - "cpanm Digest::MD5"
   - "cpanm HTML::Entities"
   - "cpanm Math::BigFloat"
   - "cpanm IO::File"
   - "cpanm IO::Scalar"
   - "cpanm Encode"
   - "cpanm Time::Local"
   - "cpanm Cwd"
   - "cpanm Config::Std"
   - "cpanm Mojo::Base"
   - "cpanm MIME::Lite"
   - "cpanm Template"
   - "cpanm Error"
   - "cpanm CGI::Simple"
   - "cpanm File::MimeInfo"
script:
   export RELEASE_TESTING=1 && perl Makefile.PL && sh tools/pre-release-tests.sh && cover -test -report coveralls
